version: '3.3'

services:

  redis:
    image: redis:7.0.7
    command: bash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    env_file: .env
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_celery.sh
    #command: bash -c "celery -A config worker --beat --scheduler django --pool prefork --loglevel=info" # info,debug # bash -c "celery multi start 1"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  flower:
    build:
      context: ./backend
    depends_on:
      - celery
    volumes:
      - ./backend:/opt
    command: bash -c "celery -A config flower"
    ports:
      - "5555:5555"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

# docker-compose -f docker-compose-celery.yml -p prup-celery up