version: '3.3'

services:
  celery:
    build:
      context: ./backend
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_celery.sh
    #command: bash -c "celery -A config worker --beat --scheduler django --pool prefork --loglevel=info" # info,debug # bash -c "celery multi start 1"
    env_file: .env
    networks:
      - proxynet

  flower:
    build:
      context: ./backend
    depends_on:
      - celery
    volumes:
      - ./backend:/opt
    command: bash -c "cd /opt && celery -A config flower --basic-auth=${FLOWER_ID}:${FLOWER_PW}"
    ports:
      - "5555:5555"
    env_file: .env
    networks:
      - proxynet

networks:
  proxynet:
    external: true
