version: '3.3'
name: django_local
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_local
    #restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_local.sh
    ports:
      - "3210:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx/
      - ./nginx/ssl:/usr/share/nginx/ssl/

  postgres:
    image: postgres:13
    #restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
    ports:
      - "54321:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0.7
    #docker-compose up --build
    #docker-compose down --volumes --remove-orphans
