version: '3.3'
name: django_local
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_local
    #restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_local.sh
    env_file: .env
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/error-page.conf:/etc/nginx/snippets/error-page.conf:ro
      - ./nginx/log:/var/log/nginx/
      - ./nginx/ssl:/usr/share/nginx/ssl/
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/listing:/usr/share/nginx/listing/
      - F:\:/usr/share/nginx/listing/media/

  postgres:
    image: postgres:13
    #restart: always
    env_file: .env
    ports:
      - "54321:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  redis:
    image: redis:7.0.7

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile_local
    depends_on:
      - backend
    volumes:
      - ./backend:/opt
    command: bash -c "celery -A config worker --loglevel=info"
    env_file: .env
