version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_server.sh
    env_file: .env
    ports:
      - "3030:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx_devel.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.celery.conf:/etc/nginx/nginx.celery.conf:ro
      - ./nginx/error-page.conf:/etc/nginx/snippets/error-page.conf:ro
      - ./nginx/log:/var/log/nginx/
      - ./nginx/ssl:/usr/share/nginx/ssl/
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/react:/usr/share/nginx/react/
      - ./nginx/listing:/usr/share/nginx/listing/
      #- F:\:/usr/share/nginx/listing/media/
    ports:
      - "80:80"
      - "443:443"

  postgres:
    build:
      context: ./postgres
    # image: postgres:13
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" # 이렇게 해야 kafka connect에서 jdbc connect를 사용할 수 있다
    env_file: .env
    ports:
      - "54320:5432"
  
  redis:
    image: redis:7.0.7
    command: bash -c "redis-server --requirepass ${REDIS_PASSWORD}" # redis-cli 인증 : auth default password
    env_file: .env

  celery:
    build:
      context: ./backend
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_celery.sh
    env_file: .env

  flower:
    build:
      context: ./backend
    depends_on:
      - celery
    volumes:
      - ./backend:/opt
    command: bash -c "cd /opt && celery -A config flower --basic-auth=${FLOWER_ID}:${FLOWER_PW}"
    ports:
      - "5555:5555"
    env_file: .env

# docker-compose -f docker-compose.yml -p <<원하는 이름>> up
