version: '3.3'

services:
  backend_a:
    container_name: backend_a
    build:
      context: ./backend
    command: /opt/scripts/start_server.sh
    env_file: .env
    volumes:
      - ./backend/log/:/opt/log/
      - ./backend/media/:/opt/media/
      - ./backend/staticfiles/:/opt/staticfiles/
    networks:
      - proxynet

  backend_b:
    container_name: backend_b
    build:
      context: ./backend
    command: /opt/scripts/start_server.sh
    env_file: .env
    volumes:
      - ./backend/log/:/opt/log/
      - ./backend/media/:/opt/media/
      - ./backend/staticfiles/:/opt/staticfiles/
    networks:
      - proxynet

  channels:
    container_name: channels
    build:
      context: ./backend
    volumes:
      - ./backend:/opt
    command: /opt/scripts/start_channels.sh
    env_file: .env
    networks:
      - proxynet

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx_rolling.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxynet
    ports:
      - 88:88

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail:/mnt/config
      - ./backend/log:/var/log
    networks:
      - proxynet
    env_file: .env
    command:
      - -config.file=/mnt/config/promtail-config.yml
      - -config.expand-env=true

networks:
  proxynet:
    external: true

# docker-compose -f docker-compose.yml -p <<원하는 이름>> up
