version: '3.3'

volumes:
  vpp_data: {}

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/opt
      - ~/.aws:/root/.aws:ro
    command: /opt/scripts/start.sh
    entrypoint: /opt/scripts/entrypoint.sh
    restart: always

  postgres:
    image:
    env:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx/
