version: '3.3'

services:

  redis:
    image: redis:7.0.7
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
    volumes:
      - ./backend:/opt
    command: bash -c "celery -A config worker --pool prefork --loglevel=info"
    # command: bash -c "celery multi start 1"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  flower:
    build:
      context: ./backend
    depends_on:
      - celery
    volumes:
      - ./backend:/opt
    command: bash -c "celery -A config flower"
    ports:
      - "5555:5555"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env

# docker-compose -f docker-compose-celery.yml -p prup-celery up