# Generated by Django 4.1.4 on 2023-04-08 10:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(blank=True, null=True, verbose_name='언제')),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Red'), (2, 'Orange'), (3, 'Yello'), (4, 'Green'), (5, 'Blue'), (6, 'Indigo'), (7, 'Purple'), (8, 'Black'), (9, 'White'), (10, 'Gray')], default=1, null=True, verbose_name='레벨')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='내 점수')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='메모')),
                ('picture', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='사진명'), blank=True, null=True, size=None)),
                ('video', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='비디오명'), blank=True, null=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='태그'), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정일')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자 id')),
            ],
            options={
                'verbose_name_plural': '축구 기록',
                'db_table': 'soccer',
            },
        ),
        migrations.CreateModel(
            name='SoccerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('soccer_time', models.TimeField(blank=True, null=True, verbose_name='운동 시간 = 종료시간 - 시간시작')),
                ('soccer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soccer_time', to='soccer.soccer', verbose_name='soccer id')),
            ],
            options={
                'verbose_name_plural': '축구 시간',
                'db_table': 'soccer_time',
            },
        ),
        migrations.CreateModel(
            name='SoccerPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='장소')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
            ],
            options={
                'verbose_name_plural': '축구 장소',
                'db_table': 'soccer_place',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.AddField(
            model_name='soccer',
            name='where',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soccer_place', to='soccer.soccerplace', verbose_name='place id'),
        ),
        migrations.CreateModel(
            name='SoccerWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soccer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soccer_with', to='soccer.soccer', verbose_name='soccer id')),
                ('user_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='with_user_from', to=settings.AUTH_USER_MODEL, verbose_name='사용자 id')),
                ('user_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='with_user_to', to=settings.AUTH_USER_MODEL, verbose_name='사용자 id')),
            ],
            options={
                'verbose_name_plural': '축구 함께',
                'db_table': 'soccer_with',
                'unique_together': {('user_from', 'user_to', 'soccer')},
            },
        ),
    ]
