# Generated by Django 4.1.4 on 2023-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='code',
            field=models.TextField(null=True, verbose_name='코드'),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.TextField(null=True, verbose_name='파일 명'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
