# Generated by Django 4.1.4 on 2023-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_remove_file_content_remove_file_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.TextField(null=True, verbose_name='파일 경로'),
        ),
    ]
