# Generated by Django 4.1.4 on 2023-03-05 04:18

from django.db import migrations
from api.v1.user.models import CustomUserManager


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_last_login_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", CustomUserManager()),
            ],
        ),
    ]
