server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions.yaml

clients:
  - url: http://host.docker.internal:7100/loki/api/v1/push

# {job="django"}
scrape_configs:
- job_name: django
  static_configs:
  - targets:
      - localhost
    labels:
      job: django
      __path__: /var/log/response.log

# - job_name: syslog
#   syslog:
#     listen_address: 0.0.0.0:1514
#     labels:
#       job: "syslog"
#   relabel_configs:
#     - source_labels: ["__syslog_connection_ip_address"]
#       target_label: "ip_address"
#     - source_labels: ["__syslog_message_severity"]
#       target_label: "severity"
#     - source_labels: ["__syslog_message_facility"]
#       target_label: "facility"
#     - source_labels: ["__syslog_message_app_name"]
#       target_label: "app_name"
#     - source_labels: ["__syslog_message_hostname"]
#       target_label: "host"
