positions:
  filename: /positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: info
    static_configs:
    - targets:
        - localhost
      labels:
        job: info_logs
        __path__: /var/log/*.log

scrape_configs:
  - job_name: error
    static_configs:
    - targets:
        - localhost
      labels:
        job: error_logs
        __path__: /var/log/*.err

# - job_name: syslog
#   syslog:
#     listen_address: 0.0.0.0:1514
#     labels:
#       job: "syslog"
#   relabel_configs:
#     - source_labels: ["__syslog_connection_ip_address"]
#       target_label: "ip_address"
#     - source_labels: ["__syslog_message_severity"]
#       target_label: "severity"
#     - source_labels: ["__syslog_message_facility"]
#       target_label: "facility"
#     - source_labels: ["__syslog_message_app_name"]
#       target_label: "app_name"
#     - source_labels: ["__syslog_message_hostname"]
#       target_label: "host"
