name: deploy

on:
  push:
    branches:
      - main
jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }} # 내가 변수로 저장한 ip
          username: ${{ secrets.PROD_USER }} # 내가 변수로 저장한 User
          password: ${{ secrets.PROD_PEM }} # 내가 변수로 저장한 pem key
          script: |
            cd ~/git/Django_Template # 내가 Clone한 폴더 안으로 들어간다.
            git pull # 자동으로 pull해서 주기적 업데이트
            docker ps
